## Dont change it is used in AUTOGENERATION of a specific file ##
## Dest: deploy/k8s/environment/staging/kustomization.yaml ##
## Source: site.j2 ##
---
namespace: default
replicas:
  - name: wordpress
images:
  - newName: ghcr.io/miteshshah/docker
    name: placeholder-base-image
    newTag: 10a2925
resources:
  - ../../base
