apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubeissuer-wp
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hello@kubernetes.io
    privateKeySecretRef:
      name: kubeissuer-wp
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert-wp
spec:
  secretName: tls-wp
  issuerRef:
    name: kubeissuer-wp
    kind: ClusterIssuer
  commonName: mi-k8s.rt.gw
  dnsNames:
  - mi-k8s.rt.gw
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: kubeissuer-wp
    kubernetes.io/ingress.class: nginx
  name: kube-certs-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - mi-k8s.rt.gw
    secretName: tls-wp

  rules:
  - host: mi-k8s.rt.gw
    http:
      paths:
      - backend:
          service:
            name: wordpress
            port:
              number: 80
        path: /
        pathType: Prefix
