name: build-push-wp-fpm-ghcr

on:
  workflow_dispatch:
  push:
    branches: [k8s]

jobs:

  build-push-wordpress:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    defaults:
      run:
        working-directory: '.'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set enviroment
        shell: bash
        # env:
        #   db_connection: ${{secrets.GSQL_CONNECTION}}
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Inventory Image
        env:
          TAG_NAME: ${{github.ref_name}}
          sha: ${{ env.sha_short }}
        run: |
          echo "Github Ref name ${TAG_NAME} $sha"
          docker build . --tag ghcr.io/miteshshah/docker:$sha
          docker push ghcr.io/miteshshah/docker:$sha


      - name: Generate deploy manifest from Jinja template
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: deploy/site.j2
          output_file: deploy/k8s/environment/staging/kustomization.yaml
          strict: true
          variables: |
            image_deploy_tag=${{ env.sha_short }}

      - name: Commit deploy manifest on local repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -s -m "[skip ci] Generate deployment manifests"
          git push
